### ISSUE TITLE
Access denied with multiple databases

### ISSUE THREAD

**Issue by sschuchlenz** [OCA/connector#163]
I've set up the jobrunner on a multi-database installation but when I omit `--database <DATABASE_NAME>` from the odoo start script in `/etc/init.d/` I get  `Access denied` error messages in my odoo log:

`2015-12-27 09:43:04,780 1205 INFO ? openerp.addons.connector.jobrunner.runner: initializing database connections
2015-12-27 09:43:04,780 1205 ERROR ? openerp.addons.connector.jobrunner.runner: exception: sleeping 5s and retrying
Traceback (most recent call last):
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/connector/jobrunner/runner.py", line 344, in run
    self.initialize_databases()
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/connector/jobrunner/runner.py", line 285, in initialize_databases
    for db_name in self.get_db_names():
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/connector/jobrunner/runner.py", line 267, in get_db_names
    db_names = openerp.service.db.exp_list()
  File "/usr/lib/python2.7/dist-packages/openerp/service/db.py", line 309, in exp_list
    raise openerp.exceptions.AccessDenied()
AccessDenied: Access denied.`

My line for starting odoo looks like that:

`start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $USER:$USER --background --make-pidfile --exec $DAEMON -- --config $CONFIG --logfile $LOGFILE
 --load=web,connector --workers=4 --db-filter='^%d$' --log-level=debug --longpolling-port=8072`

(all params are correctly configured and when I add `--database <DATABASE_NAME>` the errors go away but odoo executes only the jobs from the specified db name.

Is there a way to pass `--database='^%d$'` or something like that? Please advise.

**Comment by sbidoul** [comment]
@sschuchlenz is it possible that you have list_db = False in your config file?

Anyway I think it's a bug. #164 should fix it. Can you test it?

**Comment by sschuchlenz** [comment]
@sbidoul yes, list_db was set to false, this fixes it. big thanks for the quick reply, I will try #164 though. only problem still persisting is that the Magento connector does not execute any jobs but I reckon this is something specific to this connector and can't really be answered here.

**Comment by sbidoul** [comment]
@sschuchlenz make sure you carefully follow instructions at http://odoo-connector.com/guides/jobrunner.html
